### PR TITLE
Fix build breaks with the latest Arduino IDE and TimeLib

### PR DESCRIPTION
**Pull request by jkotas**
- Wrong Time.h included. Use TimeLib.h instead to avoid the name collision.
- Compiler requires PROGMEM data to be const
- Serial1 does not exist anymore

### CODE REVIEW

**Comment by jkotas** [comment]
Building and uploading works with these changes in the latest Arduino IDE. However, the clock runs twice as fast than normal. The problem is `millis()` increments twice as fast than normal. Looks like the interrupt frequency used to update `millis()` is not right. We have worked around it by dividing `millis()` by 2, but that is not the right fix. Not sure where to look to make the right fix.

**Comment by oskay** [comment]
I'll have to take a look at this and evaluate the new time library. It seems to change every once in a while.

**Comment by oskay** [comment]
It could be the case that the interrupt is attached twice -- incrementing twice at each millis marker.

**Comment by oskay** [comment]
I've updated the codebase with the current-generation time library, and it seems to compile and run correctly without fudging the clock rate.

**Pull request closed without merging**
